"""add stripe invoice and customer fields

Revision ID: abe43d5e7471
Revises: e1da7e060a7c
Create Date: 2026-07-01 15:28:43.555084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abe43d5e7471'
down_revision: Union[str, None] = 'e1da7e060a7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.add_column('invoices', sa.Column('hosted_invoice_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'hosted_invoice_url')
    op.drop_column('clients', 'stripe_customer_id')
    # ### end Alembic commands ###
